<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.9">
  <POU Name="F_TargetReached" Id="{b4785d9c-3817-4f5c-9628-573167cb6cb1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_TargetReached : BOOL
VAR_INPUT
	fCurrentPos: LREAL;
	fTargetPos: LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
F_TargetReached := F_TargetWindowReached(fCurrentPos, fTargetPos, fEpsilon);
]]></ST>
    </Implementation>
    <LineIds Name="F_TargetReached">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>